/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.Services.TrainService;
import ticket.booking.Services.UserBookingService;
import ticket.booking.booking.entities.Train;
import ticket.booking.booking.entities.User;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {


    public static void main(String[] args) throws IOException {
        System.out.println("Running Train Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch (IOException ex){
            ex.printStackTrace();
            return;
        }
        Train trainSelectedForBooking = null;
        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit");
            option = sc.nextInt();
            switch ((option)){
                case 1:
                    System.out.println("Enter name");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter password");
                    String passwordToSignUp = sc.next();

                    User UserSignUp = new User(nameToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(),UUID.randomUUID().toString());
                    userBookingService.signUp(UserSignUp);
                    break;

                case 2:
                    System.out.println("Enter name");
                    String nameToLogIn = sc.next();
                    System.out.println("Enter password");
                    String passwordToLogIn = sc.next();

                    User UserLogIn = new User(nameToLogIn, passwordToLogIn,new ArrayList<>(),UUID.randomUUID().toString());
                    userBookingService = new UserBookingService(UserLogIn);
                    Boolean loggedIn = userBookingService.loginUser();

                    if(loggedIn){
                        System.out.println("login successful");
                    }
                    else {
                        System.out.println("Invalid credentials");
                    }
                    break;

                case 3:
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Enter source");
                    String source = sc.next();
                    System.out.println("Enter destination");
                    String destination = sc.next();
                    TrainService trainService = new TrainService();
                    List<Train> trains = trainService.searchTrains(source, destination);
                    if(trains.isEmpty()) {
                        System.out.println("No trains found");
                    } else {
                        trains.forEach(t -> System.out.println(t.getTrainName() + " - " + t.getTrainNumber()));
                        System.out.println("Select train number (1,2,3...)");
                        int trainIndex = sc.nextInt();
                        trainSelectedForBooking = trains.get(trainIndex - 1);
                        System.out.println("Selected: " + trainSelectedForBooking.getTrainName());
                    }
                    break;

                case 5:
                    System.out.println("Enter row");
                    int row = sc.nextInt();
                    System.out.println("Enter column");
                    int col = sc.nextInt();
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if(booked) {
                        System.out.println("Seat booked successfully!");
                    } else {
                        System.out.println("Seat not available");
                    }
                    break;

                case 6:
                    System.out.println("Enter ticket id to cancel");
                    String ticketID = sc.next();
                    userBookingService.cancelTicket(ticketID);
                    System.out.println("Ticket cancelled");
                    break;

            }

        }
    }
}
